# Generated by Django 4.1 on 2022-09-07 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('event_name', models.CharField(max_length=150)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_location', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
