# Generated by Django 4.1 on 2022-09-07 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=150, verbose_name='Nome do Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='holder_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Anfitrião(ões)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Exibir Página'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_lists', to='core.event')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'db_table': 'gift_lists',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=False, verbose_name='Mostrar na lista')),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.giftlist')),
            ],
            options={
                'verbose_name': 'Presente',
                'verbose_name_plural': 'Presentes',
                'db_table': 'gifts',
            },
        ),
    ]
